version: "3"

networks:
  rede:

services:
  ngnix-proxy:
    build: ./ngnix-proxy
    image: "ngnix-proxy"
    depends_on: 
      - api-tiporeembolso
      - api-reembolsos
      - api-usuarios
      - api-tipousuario
      - api-pecas
      - api-cveiculo
      - api-veiculos
      - api-estoquepecas
      - api-multas
      - api-manutencao
      - api-clientes
    networks:
      - rede
    ports:
      - "80:80"
  api-multas:
    build: ./api-multas
    image: "api-multas"
    container_name: api-multas
    networks:
      - rede
    environment:
      - ROTA=api/multas/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
  api-clientes:
    build: ./api-clientes
    image: "api-clientes"
    container_name: api-clientes
    networks:
      - rede
    environment:
      - ROTA=api/clientes/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
  api-reembolsos:
    build: ./api-reembolsos
    image: "api-reembolsos"
    container_name: api-reembolsos
    networks:
      - rede
    environment:
      - ROTA=api/reembolsos/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
  api-cveiculo:
    build: ./api-cveiculo
    image: "api-cveiculo"
    container_name: api-cveiculo
    networks:
      - rede
    environment:
      - ROTA=api/veiculos/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
  api-manutencao:
    build: ./api-manutencao
    image: "api-manutencao"
    container_name: api-manutencao
    networks:
      - rede
    environment:
      - ROTA=api/manutencoes/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
  api-veiculos:
    build: ./api-veiculos
    image: "api-veiculos"
    container_name: api-veiculos
    networks:
      - rede
    environment:
      - ROTA=api/tipoveiculos/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
  api-estoquepecas:
    build: ./api-estoquepecas
    image: "api-estoquepecas"
    container_name: api-estoquepecas
    networks:
      - rede
    environment:
      - ROTA=api/estoquepecas/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
  api-tiporeembolso:
    build: ./api-tiporeembolso
    image: "api-tiporeembolso"
    container_name: api-tiporeembolso
    networks:
      - rede
    environment:
      - ROTA=api/tiporeembolso/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
  api-tipousuario:
    build: ./api-tipousuario
    image: "api-tipousuario"
    container_name: api-tipousuario
    networks:
      - rede
    environment:
      - ROTA=api/tipousuario/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
  api-pecas:
    build: ./api-pecas
    image: "api-pecas"
    container_name: api-pecas
    networks:
      - rede
    environment:
      - ROTA=api/pecas/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
  api-usuarios:
    build: ./api-usuarios
    image: "api-usuarios"
    container_name: api-usuarios
    networks:
      - rede
    environment:
      - ROTA=api/usuarios/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
  banco-dados:
    build: ./banco-sql
    image: "banco-sql"
    container_name: "banco-dados"
    networks:
      - rede
    ports:
      - "1435:1433"
