version: "3"

networks:
  rede:

services:
  ngnix-proxy:
    build: ./ngnix-proxy
    image: "ngnix-proxy"
    networks:
      - rede
    ports:
      - "80:80"
  api-multas:
    build: ./api-multas
    image: "api-multas"
    container_name: api-multas
    networks:
      - rede
    environment:
      - ROTA=api/multas/documentacao
      - SERVER_BD=banco-dados
      - USER_BD=sa
      - PASSWORD_BD=Password@123
    ports:
      - "81:80"
  banco-dados:
    build: ./banco-sql
    image: "banco-sql"
    container_name: "banco-dados"
    networks:
      - rede
    ports:
      - "1435:1433"
