USE [FrotaVeiculos]
GO
/****** Object:  Table [dbo].[CCLIENTES]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CCLIENTES](
	[COID] [int] IDENTITY(1,1) NOT NULL,
	[COCPF] [varchar](14) NULL,
	[CONOMECLI] [varchar](200) NULL,
 CONSTRAINT [CCLIENTES_PK] PRIMARY KEY CLUSTERED 
(
	[COID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CEMAILS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CEMAILS](
	[CEID] [int] IDENTITY(1,1) NOT NULL,
	[CECNPJCPF] [varchar](14) NULL,
	[CEEMAIL] [varchar](200) NULL,
	[CETIPO] [int] NULL,
	[CEACEITARECEBER] [int] NULL,
 CONSTRAINT [CEMAILS_PK] PRIMARY KEY CLUSTERED 
(
	[CEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CENDERECO]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CENDERECO](
	[CEID] [int] IDENTITY(1,1) NOT NULL,
	[CERUA] [varchar](200) NULL,
	[CENUMERO] [varchar](20) NULL,
	[CECOMPLEMENTO] [varchar](20) NULL,
	[CEBAIRRO] [varchar](50) NULL,
	[CECIDADE] [varchar](50) NULL,
	[CEUF] [varchar](50) NULL,
	[CEPAIS] [varchar](50) NULL,
	[CELOCALIZACAOGOOGLE] [varchar](50) NULL,
 CONSTRAINT [CENDERECO_PK] PRIMARY KEY CLUSTERED 
(
	[CEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CESTOQUEPECAS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CESTOQUEPECAS](
	[CMID] [int] IDENTITY(1,1) NOT NULL,
	[CMIDPECA] [int] NULL,
	[CMPLACAVEICULO] [varchar](7) NULL,
	[CMDESCRICAO] [varchar](1000) NULL,
	[CMIDMANUTENCAO] [int] NULL,
 CONSTRAINT [CESTOQUEPECAS_PK] PRIMARY KEY CLUSTERED 
(
	[CMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMANUTENCAO]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMANUTENCAO](
	[CMID] [int] IDENTITY(1,1) NOT NULL,
	[CMPLACAVEICULO] [varchar](7) NULL,
	[CMDESCRICAO] [varchar](1000) NULL,
	[CMTIPOMANUTENCAO] [varchar](50) NULL,
	[CMPECAUSADA] [varchar](50) NULL,
	[CMVALOR] [float] NULL,
 CONSTRAINT [CMANUTENCAO_PK] PRIMARY KEY CLUSTERED 
(
	[CMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMULTAS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMULTAS](
	[CMID] [int] IDENTITY(1,1) NOT NULL,
	[CMCODIGOMULTA] [int] NOT NULL,
	[CMDTHRINFRACAO] [datetime] NOT NULL,
	[CMDTHRRECEBIMENTO] [datetime] NULL,
	[CMLOCAL] [varchar](200) NULL,
	[CMPONTOS] [int] NULL,
	[CMVALOR] [float] NULL,
	[CMPLACA] [varchar](7) NOT NULL,
 CONSTRAINT [CMULTAS_PK] PRIMARY KEY CLUSTERED 
(
	[CMPLACA] ASC,
	[CMCODIGOMULTA] ASC,
	[CMDTHRINFRACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COCUPANTES]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COCUPANTES](
	[COID] [int] IDENTITY(1,1) NOT NULL,
	[COIDVIAGEM] [int] NULL,
 CONSTRAINT [COCUPANTES_PK] PRIMARY KEY CLUSTERED 
(
	[COID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPROPIETARIOS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPROPIETARIOS](
	[CPID] [int] IDENTITY(1,1) NOT NULL,
	[CPCGC] [varchar](14) NOT NULL,
	[CPNOME] [varchar](200) NULL,
 CONSTRAINT [CPROPIETARIOS_PK] PRIMARY KEY CLUSTERED 
(
	[CPCGC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CREEMBOLSOS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CREEMBOLSOS](
	[CRID] [int] IDENTITY(1,1) NOT NULL,
	[CRTIPO] [int] NULL,
	[CRPLACAVEICULO] [varchar](7) NULL,
	[CRIDENDERECO] [int] NULL,
	[CRVALOR] [float] NULL,
	[CRDTHRCAD] [datetime] NULL,
	[CRDTHRINI] [datetime] NULL,
	[CRDTHRFIM] [datetime] NULL,
 CONSTRAINT [CREEMBOLSOS_PK] PRIMARY KEY CLUSTERED 
(
	[CRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CSEGURO]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CSEGURO](
	[CCID] [int] IDENTITY(1,1) NOT NULL,
	[CCPLACAVEICULO] [varchar](7) NULL,
	[CCSEGURADORA] [varchar](200) NULL,
	[CCCONTRATOLOCACAO] [varchar](20) NULL,
	[CCDTINIVIGENCIA] [datetime] NULL,
	[CCDTFIMVIGENCIA] [datetime] NULL,
	[CCVALORSEGURO] [float] NULL,
 CONSTRAINT [CSEGURO_PK] PRIMARY KEY CLUSTERED 
(
	[CCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CSINISTRO]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CSINISTRO](
	[CSID] [int] IDENTITY(1,1) NOT NULL,
	[CSPLACAVEICULO] [varchar](7) NULL,
	[CSIDSEGURO] [int] NULL,
	[CSDESCRICAO] [varchar](1000) NULL,
 CONSTRAINT [CSINISTRO_PK] PRIMARY KEY CLUSTERED 
(
	[CSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTELEFONES]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTELEFONES](
	[CTID] [int] IDENTITY(1,1) NOT NULL,
	[CTCNPJCPF] [varchar](14) NULL,
	[CTDD] [int] NULL,
	[CTNUMERO] [int] NULL,
	[CTTIPO] [int] NULL,
	[CTOPERADORA] [int] NULL,
 CONSTRAINT [CTELEFONES_PK] PRIMARY KEY CLUSTERED 
(
	[CTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSUARIOS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSUARIOS](
	[CUID] [int] IDENTITY(1,1) NOT NULL,
	[CUNOME] [varchar](200) NULL,
	[CUCNPJCPF] [varchar](14) NOT NULL,
	[CUCNH] [varchar](20) NULL,
	[CURG] [varchar](11) NULL,
	[CUTPUSUARIO] [int] NULL,
	[CUIDENDERECO] [int] NULL,
	[CUCARTEIRATRABALHO] [varchar](20) NULL,
	[CUDATAVALIDADECNH] [datetime] NULL,
	[CUDATAULTIMOEXAMEMEDICO] [datetime] NULL,
 CONSTRAINT [CUSUARIOS_PK] PRIMARY KEY CLUSTERED 
(
	[CUCNPJCPF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CVEICULOS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CVEICULOS](
	[CVCGC_PROPIETARIO] [varchar](14) NULL,
	[CVPLACA] [varchar](7) NOT NULL,
	[CVCHASSI] [varchar](17) NULL,
	[CVMODELO] [varchar](20) NULL,
	[CVMARCAR] [varchar](30) NULL,
	[CVCOR] [varchar](10) NULL,
	[CVANO] [int] NULL,
	[CVTIPOVEICULO] [int] NULL,
	[CVQUILOMETRAGEM] [int] NULL,
	[CVVALIDADESEGURO] [datetime] NULL,
	[CVNOMESEGURADORA] [varchar](50) NULL,
	[CVNUMEROAPOLICE] [int] NULL,
 CONSTRAINT [CVEICULOS_PK] PRIMARY KEY CLUSTERED 
(
	[CVPLACA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LLOCACAO]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LLOCACAO](
	[LLID] [int] IDENTITY(1,1) NOT NULL,
	[LLUSUARIOCAD] [int] NULL,
	[LLIDCLIENTE] [int] NULL,
	[LLPLACAVEICULO] [varchar](7) NULL,
	[LLDTHRCAD] [datetime] NULL,
	[LLDTHRINICIO] [datetime] NULL,
	[LLDTHRFINAL] [datetime] NULL,
	[LLIDSEGUROCONTRATADO] [int] NULL,
	[LLVALORDIALOCACAO] [float] NULL,
 CONSTRAINT [LLOCACAO_PK] PRIMARY KEY CLUSTERED 
(
	[LLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LVIAGENS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LVIAGENS](
	[LVID] [int] IDENTITY(1,1) NOT NULL,
	[LVDTHRCAD] [datetime] NULL,
	[LVDTHRINICIO] [datetime] NULL,
	[LVDTHRFINAL] [datetime] NULL,
	[LVPLACAVEICULO] [varchar](7) NULL,
	[LVIDENDERECOORIGEM] [int] NULL,
	[LVIDENDERECODESTINO] [int] NULL,
	[LVPREVISAOKM] [int] NULL,
 CONSTRAINT [LVIAGENS_PK] PRIMARY KEY CLUSTERED 
(
	[LVID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TPECAS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TPECAS](
	[TPID] [int] IDENTITY(1,1) NOT NULL,
	[TPDESCRICAO] [varchar](50) NULL,
	[TPDATAUSO] [datetime] NULL,
	[TPVALORPECA] [float] NULL,
 CONSTRAINT [TPECAS_PK] PRIMARY KEY CLUSTERED 
(
	[TPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TREEMBOLSOS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TREEMBOLSOS](
	[TRID] [int] IDENTITY(1,1) NOT NULL,
	[TRDESCRICAO] [varchar](50) NULL,
 CONSTRAINT [TREEMBOLSOS_PK] PRIMARY KEY CLUSTERED 
(
	[TRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TUSUARIO]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TUSUARIO](
	[TUID] [int] IDENTITY(1,1) NOT NULL,
	[TUDESCRICAO] [varchar](20) NULL,
	[TUCAMPOSOBRIGATORIOS] [varchar](50) NULL,
 CONSTRAINT [TUSUARIO_PK] PRIMARY KEY CLUSTERED 
(
	[TUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TVEICULOS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TVEICULOS](
	[TVID] [int] IDENTITY(1,1) NOT NULL,
	[TVDESCRICAOTIPO] [varchar](50) NULL,
 CONSTRAINT [TVEICULOS_PK] PRIMARY KEY CLUSTERED 
(
	[TVID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIOS]    Script Date: 10/12/2019 22:48:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](200) NULL,
	[EMAIL] [varchar](200) NULL,
	[DATAHORACRIACAO] [datetime] NULL,
	[DATAHORAMODIFICACAO] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CEMAILS]  WITH NOCHECK ADD  CONSTRAINT [CEMAILS_CUSUARIOS] FOREIGN KEY([CECNPJCPF])
REFERENCES [dbo].[CUSUARIOS] ([CUCNPJCPF])
GO
ALTER TABLE [dbo].[CEMAILS] NOCHECK CONSTRAINT [CEMAILS_CUSUARIOS]
GO
ALTER TABLE [dbo].[CESTOQUEPECAS]  WITH NOCHECK ADD  CONSTRAINT [CESTOQUEPECAS_CESTOQUEPECAS] FOREIGN KEY([CMIDPECA])
REFERENCES [dbo].[TPECAS] ([TPID])
GO
ALTER TABLE [dbo].[CESTOQUEPECAS] NOCHECK CONSTRAINT [CESTOQUEPECAS_CESTOQUEPECAS]
GO
ALTER TABLE [dbo].[CESTOQUEPECAS]  WITH NOCHECK ADD  CONSTRAINT [CESTOQUEPECAS_CMANUTENCAO] FOREIGN KEY([CMIDMANUTENCAO])
REFERENCES [dbo].[CMANUTENCAO] ([CMID])
GO
ALTER TABLE [dbo].[CESTOQUEPECAS] NOCHECK CONSTRAINT [CESTOQUEPECAS_CMANUTENCAO]
GO
ALTER TABLE [dbo].[CESTOQUEPECAS]  WITH NOCHECK ADD  CONSTRAINT [CESTOQUEPECAS_CVEICULO] FOREIGN KEY([CMPLACAVEICULO])
REFERENCES [dbo].[CVEICULOS] ([CVPLACA])
GO
ALTER TABLE [dbo].[CESTOQUEPECAS] NOCHECK CONSTRAINT [CESTOQUEPECAS_CVEICULO]
GO
ALTER TABLE [dbo].[CMANUTENCAO]  WITH NOCHECK ADD  CONSTRAINT [CMANUTENCAO_CVEICULO] FOREIGN KEY([CMPLACAVEICULO])
REFERENCES [dbo].[CVEICULOS] ([CVPLACA])
GO
ALTER TABLE [dbo].[CMANUTENCAO] NOCHECK CONSTRAINT [CMANUTENCAO_CVEICULO]
GO
ALTER TABLE [dbo].[CMULTAS]  WITH NOCHECK ADD  CONSTRAINT [CMULTAS_VEICULO] FOREIGN KEY([CMPLACA])
REFERENCES [dbo].[CVEICULOS] ([CVPLACA])
GO
ALTER TABLE [dbo].[CMULTAS] NOCHECK CONSTRAINT [CMULTAS_VEICULO]
GO
ALTER TABLE [dbo].[COCUPANTES]  WITH NOCHECK ADD  CONSTRAINT [COCUPANTES_LVIAGENS] FOREIGN KEY([COIDVIAGEM])
REFERENCES [dbo].[LVIAGENS] ([LVID])
GO
ALTER TABLE [dbo].[COCUPANTES] NOCHECK CONSTRAINT [COCUPANTES_LVIAGENS]
GO
ALTER TABLE [dbo].[CREEMBOLSOS]  WITH NOCHECK ADD  CONSTRAINT [CREEMBOLSOS_CENDERECO] FOREIGN KEY([CRIDENDERECO])
REFERENCES [dbo].[CENDERECO] ([CEID])
GO
ALTER TABLE [dbo].[CREEMBOLSOS] NOCHECK CONSTRAINT [CREEMBOLSOS_CENDERECO]
GO
ALTER TABLE [dbo].[CREEMBOLSOS]  WITH NOCHECK ADD  CONSTRAINT [CREEMBOLSOS_CVEICULO] FOREIGN KEY([CRPLACAVEICULO])
REFERENCES [dbo].[CVEICULOS] ([CVPLACA])
GO
ALTER TABLE [dbo].[CREEMBOLSOS] NOCHECK CONSTRAINT [CREEMBOLSOS_CVEICULO]
GO
ALTER TABLE [dbo].[CREEMBOLSOS]  WITH NOCHECK ADD  CONSTRAINT [CREEMBOLSOS_TREEMBOLSOS] FOREIGN KEY([CRTIPO])
REFERENCES [dbo].[TREEMBOLSOS] ([TRID])
GO
ALTER TABLE [dbo].[CREEMBOLSOS] NOCHECK CONSTRAINT [CREEMBOLSOS_TREEMBOLSOS]
GO
ALTER TABLE [dbo].[CSEGURO]  WITH NOCHECK ADD  CONSTRAINT [CSEGURO_CVEICULO] FOREIGN KEY([CCPLACAVEICULO])
REFERENCES [dbo].[CVEICULOS] ([CVPLACA])
GO
ALTER TABLE [dbo].[CSEGURO] NOCHECK CONSTRAINT [CSEGURO_CVEICULO]
GO
ALTER TABLE [dbo].[CSINISTRO]  WITH NOCHECK ADD  CONSTRAINT [CSINISTRO_CSEGURO] FOREIGN KEY([CSIDSEGURO])
REFERENCES [dbo].[CSEGURO] ([CCID])
GO
ALTER TABLE [dbo].[CSINISTRO] NOCHECK CONSTRAINT [CSINISTRO_CSEGURO]
GO
ALTER TABLE [dbo].[CSINISTRO]  WITH NOCHECK ADD  CONSTRAINT [CSINISTRO_CVEICULO] FOREIGN KEY([CSPLACAVEICULO])
REFERENCES [dbo].[CVEICULOS] ([CVPLACA])
GO
ALTER TABLE [dbo].[CSINISTRO] NOCHECK CONSTRAINT [CSINISTRO_CVEICULO]
GO
ALTER TABLE [dbo].[CTELEFONES]  WITH NOCHECK ADD  CONSTRAINT [CTELEFONES_CUSUARIOS] FOREIGN KEY([CTCNPJCPF])
REFERENCES [dbo].[CUSUARIOS] ([CUCNPJCPF])
GO
ALTER TABLE [dbo].[CTELEFONES] NOCHECK CONSTRAINT [CTELEFONES_CUSUARIOS]
GO
ALTER TABLE [dbo].[CUSUARIOS]  WITH NOCHECK ADD  CONSTRAINT [CUSUARIOS_CENDERECO] FOREIGN KEY([CUIDENDERECO])
REFERENCES [dbo].[CENDERECO] ([CEID])
GO
ALTER TABLE [dbo].[CUSUARIOS] NOCHECK CONSTRAINT [CUSUARIOS_CENDERECO]
GO
ALTER TABLE [dbo].[CUSUARIOS]  WITH NOCHECK ADD  CONSTRAINT [CUSUARIOS_TUSUARIO] FOREIGN KEY([CUTPUSUARIO])
REFERENCES [dbo].[TUSUARIO] ([TUID])
GO
ALTER TABLE [dbo].[CUSUARIOS] NOCHECK CONSTRAINT [CUSUARIOS_TUSUARIO]
GO
ALTER TABLE [dbo].[CVEICULOS]  WITH NOCHECK ADD  CONSTRAINT [CVEICULOS_CPROPIETARIOS] FOREIGN KEY([CVCGC_PROPIETARIO])
REFERENCES [dbo].[CPROPIETARIOS] ([CPCGC])
GO
ALTER TABLE [dbo].[CVEICULOS] NOCHECK CONSTRAINT [CVEICULOS_CPROPIETARIOS]
GO
ALTER TABLE [dbo].[CVEICULOS]  WITH NOCHECK ADD  CONSTRAINT [CVEICULOS_TVEICULOS] FOREIGN KEY([CVTIPOVEICULO])
REFERENCES [dbo].[TVEICULOS] ([TVID])
GO
ALTER TABLE [dbo].[CVEICULOS] NOCHECK CONSTRAINT [CVEICULOS_TVEICULOS]
GO
ALTER TABLE [dbo].[LLOCACAO]  WITH NOCHECK ADD  CONSTRAINT [LLOCACAO_CCLIENTES] FOREIGN KEY([LLIDCLIENTE])
REFERENCES [dbo].[CCLIENTES] ([COID])
GO
ALTER TABLE [dbo].[LLOCACAO] NOCHECK CONSTRAINT [LLOCACAO_CCLIENTES]
GO
ALTER TABLE [dbo].[LLOCACAO]  WITH NOCHECK ADD  CONSTRAINT [LLOCACAO_CSEGURO] FOREIGN KEY([LLIDSEGUROCONTRATADO])
REFERENCES [dbo].[CSEGURO] ([CCID])
GO
ALTER TABLE [dbo].[LLOCACAO] NOCHECK CONSTRAINT [LLOCACAO_CSEGURO]
GO
ALTER TABLE [dbo].[LLOCACAO]  WITH NOCHECK ADD  CONSTRAINT [LLOCACAO_CVEICULO] FOREIGN KEY([LLPLACAVEICULO])
REFERENCES [dbo].[CVEICULOS] ([CVPLACA])
GO
ALTER TABLE [dbo].[LLOCACAO] NOCHECK CONSTRAINT [LLOCACAO_CVEICULO]
GO
ALTER TABLE [dbo].[LLOCACAO]  WITH NOCHECK ADD  CONSTRAINT [LLOCACAO_TUSUARIO] FOREIGN KEY([LLUSUARIOCAD])
REFERENCES [dbo].[TUSUARIO] ([TUID])
GO
ALTER TABLE [dbo].[LLOCACAO] NOCHECK CONSTRAINT [LLOCACAO_TUSUARIO]
GO
ALTER TABLE [dbo].[LVIAGENS]  WITH NOCHECK ADD  CONSTRAINT [LVIAGENS_CENDERECO_DESTINO] FOREIGN KEY([LVIDENDERECODESTINO])
REFERENCES [dbo].[CENDERECO] ([CEID])
GO
ALTER TABLE [dbo].[LVIAGENS] NOCHECK CONSTRAINT [LVIAGENS_CENDERECO_DESTINO]
GO
ALTER TABLE [dbo].[LVIAGENS]  WITH NOCHECK ADD  CONSTRAINT [LVIAGENS_CENDERECO_ORIGEM] FOREIGN KEY([LVIDENDERECOORIGEM])
REFERENCES [dbo].[CENDERECO] ([CEID])
GO
ALTER TABLE [dbo].[LVIAGENS] NOCHECK CONSTRAINT [LVIAGENS_CENDERECO_ORIGEM]
GO
ALTER TABLE [dbo].[LVIAGENS]  WITH NOCHECK ADD  CONSTRAINT [LVIAGENS_CVEICULO] FOREIGN KEY([LVPLACAVEICULO])
REFERENCES [dbo].[CVEICULOS] ([CVPLACA])
GO
ALTER TABLE [dbo].[LVIAGENS] NOCHECK CONSTRAINT [LVIAGENS_CVEICULO]
GO
